Repository MixinNetwork/android-app, pull requests merged in 2021-01, with the labels that each got.

#1486 Feature/qrcode
  app/src/main/java/one/mixin/android/extension/FileExtension.kt
  app/src/main/java/one/mixin/android/extension/StringExtension.kt
  app/src/main/java/one/mixin/android/job/RefreshAccountJob.kt
  app/src/main/java/one/mixin/android/ui/common/PinCodeFragment.kt
  app/src/main/java/one/mixin/android/ui/common/QrBottomSheetDialogFragment.kt
  app/src/main/java/one/mixin/android/ui/wallet/DepositAccountFragment.kt
  app/src/main/java/one/mixin/android/ui/wallet/DepositPublicKeyFragment.kt
  app/src/main/java/one/mixin/android/ui/wallet/DepositQrBottomFragment.kt
  app/src/main/java/one/mixin/android/worker/RefreshAccountWorker.kt
Labels: experimental

#2038 Copywriting errors
  app/src/main/java/one/mixin/android/widget/QuoteView.kt
Labels: bug

#2039 Fix PagedList unstable lastKey
  app/src/main/java/one/mixin/android/ui/conversation/ConversationFragment.kt
  app/src/main/java/one/mixin/android/ui/conversation/ConversationViewModel.kt
  app/src/main/java/one/mixin/android/util/KeyLivePagedListBuilder.java
  app/src/main/java/one/mixin/android/util/chat/MixinLimitOffsetDataSource.java
Labels: testing
