Repository MixinNetwork/android-app, pull requests merged in 2022-11, with the labels that each got.

#2885 Adapt landscape
  app/src/main/AndroidManifest.xml
  app/src/main/java/one/mixin/android/ui/setting/PhoneNumberSettingFragment.kt
  app/src/main/java/one/mixin/android/ui/setting/PrivacyFragment.kt
  app/src/main/java/one/mixin/android/widget/BottomSheet.kt
  app/src/main/res/layout/fragment_emergency_contact.xml
  app/src/main/res/layout/fragment_setting_mobile_contact.xml
  app/src/main/res/layout/fragment_storage_data.xml
Labels: testing

#3345 Fix handle back
  app/src/main/java/one/mixin/android/ui/setting/WalletPasswordFragment.kt
  app/src/main/java/one/mixin/android/widget/BottomSheet.kt
Labels: bug

#3374 Wallet blur background
  app/src/main/java/one/mixin/android/ui/wallet/PinCheckDialogFragment.kt
  app/src/main/java/one/mixin/android/ui/wallet/WalletFragment.kt
  app/src/main/res/layout/fragment_wallet.xml
Labels: experimental

#3289 Experimental/cache
  app/schemas/one.mixin.android.db.MixinDatabase/47.json
  app/schemas/one.mixin.android.db.pending.PendingDataBaseImp/1.json
  app/src/main/java/one/mixin/android/Constants.kt
  app/src/main/java/one/mixin/android/crypto/SignalProtocol.kt
  app/src/main/java/one/mixin/android/db/ConversationExtDao.kt
  app/src/main/java/one/mixin/android/db/DaoExtension.kt
  app/src/main/java/one/mixin/android/db/DatabaseMonitor.kt
  app/src/main/java/one/mixin/android/db/FloodMessageDao.kt
  app/src/main/java/one/mixin/android/db/JobDao.kt
  app/src/main/java/one/mixin/android/db/MixinDatabase.kt
  app/src/main/java/one/mixin/android/db/MixinDatabaseMigrations.kt
  app/src/main/java/one/mixin/android/db/pending/PendingDatabase.kt
  app/src/main/java/one/mixin/android/db/pending/PendingDatabaseImp.kt
  app/src/main/java/one/mixin/android/db/pending/PendingMessage.kt
  app/src/main/java/one/mixin/android/db/pending/PendingMessageDao.kt
  app/src/main/java/one/mixin/android/db/provider/DataProvider.kt
  app/src/main/java/one/mixin/android/di/AppModule.kt
  app/src/main/java/one/mixin/android/di/BaseDbModule.kt
  app/src/main/java/one/mixin/android/job/AttachmentDownloadJob.kt
  app/src/main/java/one/mixin/android/job/BlazeMessageService.kt
  app/src/main/java/one/mixin/android/job/ConvertDataJob.kt
  app/src/main/java/one/mixin/android/job/ConvertVideoJob.kt
  app/src/main/java/one/mixin/android/job/DecryptCallMessage.kt
  app/src/main/java/one/mixin/android/job/DecryptMessage.kt
  app/src/main/java/one/mixin/android/job/Injector.kt
  app/src/main/java/one/mixin/android/job/MessageDeleteJob.kt
  app/src/main/java/one/mixin/android/job/NotificationGenerator.kt
  app/src/main/java/one/mixin/android/job/SendAttachmentMessageJob.kt
  app/src/main/java/one/mixin/android/job/SendGiphyJob.kt
  app/src/main/java/one/mixin/android/job/SendMessageJob.kt
  app/src/main/java/one/mixin/android/job/SendTranscriptJob.kt
  app/src/main/java/one/mixin/android/job/TranscriptDeleteJob.kt
  app/src/main/java/one/mixin/android/messenger/Hedwig.kt
  app/src/main/java/one/mixin/android/messenger/HedwigImp.kt
  app/src/main/java/one/mixin/android/repository/ConversationRepository.kt
  app/src/main/java/one/mixin/android/ui/common/message/CleanMessageHelper.kt
  app/src/main/java/one/mixin/android/ui/conversation/ConversationViewModel.kt
  app/src/main/java/one/mixin/android/ui/conversation/chathistory/ChatHistoryActivity.kt
  app/src/main/java/one/mixin/android/ui/media/SharedMediaViewModel.kt
  app/src/main/java/one/mixin/android/util/MessageFts4Helper.kt
  app/src/main/java/one/mixin/android/util/chat/FastLimitOffsetDataSource.kt
  app/src/main/java/one/mixin/android/util/chat/InvalidateFlow.kt
  app/src/main/java/one/mixin/android/vo/ConversationExt.kt
  app/src/main/java/one/mixin/android/vo/ForwardMessage.kt
  app/src/main/java/one/mixin/android/vo/Job.kt
  app/src/main/java/one/mixin/android/vo/Message.kt
  app/src/main/java/one/mixin/android/webrtc/GroupCallService.kt
  app/src/main/java/one/mixin/android/webrtc/VoiceCallService.kt
  app/src/main/java/one/mixin/android/websocket/ChatWebSocket.kt
Labels: experimental

#3387 Feature/pin string
  app/src/main/java/one/mixin/android/ui/auth/AuthBottomSheetDialogFragment.kt
  app/src/main/java/one/mixin/android/ui/auth/compose/PinKeyBoard.kt
  app/src/main/java/one/mixin/android/ui/common/MultisigsBottomSheetDialogFragment.kt
  app/src/main/java/one/mixin/android/ui/common/NftBottomSheetDialogFragment.kt
  app/src/main/java/one/mixin/android/ui/common/VerifyBottomSheetDialogFragment.kt
  app/src/main/java/one/mixin/android/ui/common/biometric/BiometricDialog.kt
  app/src/main/java/one/mixin/android/ui/common/biometric/BiometricLayout.kt
  app/src/main/java/one/mixin/android/ui/conversation/transfer/TransferBottomSheetDialogFragment.kt
  app/src/main/java/one/mixin/android/ui/device/ConfirmBottomFragment.kt
  app/src/main/java/one/mixin/android/ui/setting/PinEmergencyBottomSheetDialog.kt
  app/src/main/java/one/mixin/android/ui/setting/delete/DeleteAccountPinBottomSheetDialogFragment.kt
  app/src/main/java/one/mixin/android/ui/wallet/PinAddrBottomSheetDialogFragment.kt
  app/src/main/java/one/mixin/android/ui/wallet/PinBiometricsBottomSheetDialogFragment.kt
  app/src/main/res/layout/layout_pin_biometric.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: testing

#3393 Fix insert sql
  app/src/main/java/one/mixin/android/db/ConversationExtDao.kt
Labels: bug
